In [1]:
from pycaret.datasets import get_data
data = get_data('iris')
from pycaret.classification import*

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [2]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [3]:
s = setup(data,
target='species',
numeric_features = ['sepal_length', 'sepal_width',
                    'petal_length', 'petal_width'],
session_id=42,
train_size = 0.8, 
data_split_shuffle=True,
remove_multicollinearity=True,
remove_outliers=True,
normalize=True,
normalize_method="robust",
use_gpu=False,
fold_shuffle=True,
imputation_type='iterative')

In [4]:
best_model = compare_models()

In [5]:
lda = create_model("lda")

In [6]:
tuned_model = tune_model(lda,fold=10,optimize="Accuracy",
search_library="tune-sklearn",
 search_algorithm="bayesian",
 choose_better=False,
 n_iter=5)

In [7]:
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [8]:
save_model(lda,"/home/izzet/Desktop/projects/basic_project/iris_model.pkl")

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=['sepal_length',
                                                           'sepal_width',
                                                           'petal_length',
                                                           'petal_width'],
                                       target='species', time_features=[])),
                 ('imputer',
                  Iterative_Imputer(add_indicator=False,
                                    classifier=LGBMClassifi...
                 ('fix_multi',
                  Fix_multicollinearity(correlation_with_target_preference=None,
                                        correlation_with_target_threshold=0.0,
                                        target_variable='species',
                                        threshold=0.9)),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  LinearDiscriminantAnalysis(n_components=None, priors=None,
                                             shrinkage=None, solver='svd',
                                             store_covariance=False,
                                             tol=0.0001)]],
          verbose=False),
 '/home/izzet/Desktop/projects/basic_project/iris_model.pkl.pkl')